version: "3.9"

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    environment:
      SCIBOX_API_KEY: ${SCIBOX_API_KEY}
      SCIBOX_BASE_URL: ${SCIBOX_BASE_URL:-https://api.scibox.ai/v1}
      FAQ_PATH: ${FAQ_PATH:-/app/data/smart_support_vtb_belarus_faq_final.xlsx}
    ports:
      - "8000:8000"
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    environment:
      VITE_API_BASE_URL: http://backend:8000
    ports:
      - "8080:8080"
    depends_on:
      - backend

